import time
print("  |||                   |||                 |||                                     |")
time.sleep(0.25)
print("    |    |              ||                 |   |                                    |")
time.sleep(0.25)
print("    |                  |                   |                                        |")
time.sleep(0.25)
print("    |   ||    | | ||          ||||         |       ||||   | | ||   | |||   |    |  ||||    ||||   | ||")
time.sleep(0.25)
print("    |    |    || |  |        |    |        |      |    |  || |  |  ||   |  |    |   |     |    |   |")
time.sleep(0.25)
print("    |    |    || |  |        |    |        |      |    |  || |  |  ||   |  |    |   |     |    |   |")
time.sleep(0.25)
print("    |    |    |  |  |         ||           |      |    |  |  |  |  |    |  |    |   |     ||||||   |")
time.sleep(0.25)
print("    |    |    |  |  |           ||         |      |    |  |  |  |  ||   |  |    |   |     |        |")
time.sleep(0.25)
print("|   |    |    |  |  |        |    |        |   |  |    |  |  |  |  | |||   |   ||   |  |  |    |   |")
time.sleep(0.25)
print(" |||   |||||  |  |  |         ||||          |||    ||||   |  |  |  |        ||| |    ||    ||||    |")
time.sleep(0.25)
print("                                                                   |")
time.sleep(0.25)
print("                                                                   |")

